name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Maven
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          clean verify
      - name: Extract release tag
        id: vars
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: keycloak-event-listener-rabbitmq ${{ steps.vars.outputs.version }}
          files: |
            ./target/keycloak-to-rabbit-*.jar
